set guifont=Menlo\ Regular:h15
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.


"Solarized
colorscheme solarized
set background=light        
let g:solarized_contrast="high"
