" Initialization {{{
set nocompatible                  " Must come first because it changes other options.
let mapleader = ","
silent! call pathogen#runtime_append_all_bundles() " Load pathogen

runtime! plugin/sensible.vim " Load sensible before vimrc
" }}}

" General options  {{{

set showmode                      " Display the mode you're in.

set hidden                        " Handle multiple buffers better.

set wildmode=longest:full         " Complete files like a shell.
set wildmenu

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.

set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs

set exrc                          " enable per-directory .vimrc files
set secure                        " disable unsafe commands in local .vimrc files

set history=1000                  " Command line history

set updatetime=750                " Time after stop typing before triggering events  

" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

"Autosave/Read
autocmd BufLeave,FocusLost * silent! wall
set autowrite
set autoread

"Directories for swap,undo and backup
set directory=$HOME/.local/share/vim/swap
set backupdir=$HOME/.local/share/vim/backup
set undodir=$HOME/.local/share/vim/undo
set undofile



" General options }}}

" Colour in terminal mode {{{

if !has('gui_running')
    "Use light background
    set background=dark
    " More colors in terminal 
    set t_Co=256
endif

" Diff colours
hi DiffText ctermbg=LightBlue
hi DiffAdd ctermbg=LightBlue
hi DiffChange ctermbg=LightCyan
hi DiffDelete ctermfg=Blue ctermbg=LightCyan

" }}}

" Plugin settings and configuration  {{{

"Easymotion 
"No background shading
let g:EasyMotion_do_shade = 0

let NERDTreeChDirMode=2
let NERDTreeIgnore = ['^target$','\.iml$']

let g:CommandTMaxHeight=15
let g:CommandTMinHeight=15
let g:CommandTHighlightColor='StatusLine'

" Clear input 
let g:CommandTClearMap="<C-w>"

"Snipmates support functions
source $HOME/.vim/snippets/support_functions.vim

"Syntastic
let g:syntastic_mode_map = { 'mode': 'active', 'active_filetypes': ['ruby'],'passive_filetypes': ['java','xml'] }


"Rubytest
map <LocalLeader>t <Plug>RubyTestRun     " change from <Leader>t to <Leader>\
map <LocalLeader>T <Plug>RubyFileRun     " change from <Leader>T to <Leader>]
map <LocalLeader>l <Plug>RubyTestRunLast " change from <Leader>l to <Leader>/


" Powerline
set rtp+=$HOME/dotfiles/powerline/powerline/powerline/bindings/vim
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup

" Eclim
" Disable eclim, enable by unlet:g:EclimDisable in project .vimrc 
let g:EclimDisabled=1

" Gitgutter
nmap ]h <Plug>GitGutterNextHunk
nmap [h <Plug>GitGutterPrevHunk
highlight clear SignColumn


"}}}

" File settings{{{
augroup file
  autocmd!
  autocmd BufRead,BufNewFile,BufEnter jboss-esb.xml setlocal filetype=jboss-esb syntax=xml foldmethod=syntax foldlevel=99
  autocmd BufRead,BufNewFile,BufEnter *.wsdl setlocal syntax=xml foldmethod=syntax foldlevel=99
  "Auto source vimrc files
  autocmd bufwritepost .vimrc,vimrc source $MYVIMRC
  autocmd bufwritepost .gvimrc,gvimrc source $MYGVIMRC

  " Set cursor position unless it's invalid or in an event handler
  autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal g`\"" |
      \ endif

augroup END

"}}}

" Folding {{{
let g:xml_syntax_folding=1

augroup folding
    autocmd!
    autocmd FileType xml  setlocal foldmethod=syntax foldlevel=9
    autocmd FileType java setlocal foldmethod=syntax foldlevel=9
    autocmd FileType ruby setlocal foldmethod=syntax foldlevel=9
    autocmd FileType xsd  setlocal foldmethod=syntax foldlevel=9
    autocmd FileType xslt setlocal foldmethod=syntax foldlevel=9
    autocmd FileType xsl  setlocal foldmethod=syntax foldlevel=9
    autocmd FileType vim  setlocal foldmethod=marker foldlevel=1
augroup END

" Folding }}}

" Spelling {{{
highlight clear SpellBad
highlight clear SpellCap 
highlight clear SpellRare
highlight clear SpellLocal
highlight SpellBad cterm=underline
highlight SpellCap cterm=underline
highlight SpellRare cterm=underline
highlight SpellLocal cterm=underline

augroup spelling
    autocmd!
    autocmd FileType elixir setlocal spell spelllang=elixir
augroup END

" Spelling }}}


" Mappings {{{
"Vimrc stuff
nnoremap <leader>ve :tabedit ~/dotfiles/vim/vimrc<cr>
nnoremap <leader>vs :source $MYVIMRC<cr>

"Undo tree plugin
nnoremap <F5> :GundoToggle<CR>

"NerdTree plugin
nnoremap <F3> :NERDTreeToggle<CR>
nnoremap <F4> :NERDTreeFind<CR>

"Command-t
"Find file
nnoremap <silent> <Leader>ff :CommandT .<CR>
"Find buffer
nnoremap <silent> <Leader>fb :CommandTBuffer<CR>
"Find tag
nnoremap <silent> <Leader>ft :CommandTTag<CR>
"Find jump
nnoremap <silent> <Leader>fj :CommandTJump<CR>
"Clear find
nnoremap <silent> <Leader>fc :CommandTFlush<CR>

" Search for the current selection (redux)
xnoremap * :<C-u>call <SID>VSetSearch()<CR>/<C-R>=@/<CR><CR>
xnoremap # :<C-u>call <SID>VSetSearch()<CR>?<C-R>=@/<CR><CR>

"Eclim
nnoremap <Leader>jt :JUnit<CR> 
nnoremap <Leader>jb :ProjectBuild<CR> 
nnoremap <Leader>pb :ProjectBuild<CR> 
nnoremap <Leader>jc :JavaCorrect<CR> 
nnoremap <Leader>ji :JavaImport<CR> 
nnoremap <Leader>jr :ProjectRefresh<CR> 
nnoremap <Leader>pr :ProjectRefresh<CR> 
nnoremap ]j :JavaSearchContext<CR>

"Expand active files directory
cnoremap <expr> %% getcmdtype() == ':' ? expand('%:h').'/' : '%%'

"Toggle background using same keyboard mapping style as unimpaired plugin
nnoremap cob :call ToggleBackground()<cr>

"Snippets
nnoremap <Leader>sr :call ReloadAllSnippets()<cr>

"Search and Replace Word under cursor
nnoremap <leader>r ebviw"vy:%s/\<<C-R>v\>//gc<left><left><left>

"Indent Document
nnoremap <leader>id mvggVG='v

"Use dot command line wise in visual mode
xnoremap . :norm.<CR> to vimrc

augroup mappings
autocmd!
"Canonicalize xml element. Change </test> into <test></test>
autocmd Filetype xml,xstl,xsd nmap <leader>xc 0f/x\e
augroup END

"Syntastic
nnoremap <leader>s :SyntasticCheck<CR>

" Next/previous tab
nnoremap ]w :tabnext<CR>
nnoremap [w :tabprevious<CR>
" Mappings }}}

" Commands {{{
"Xmllint
command! Xmllint  :%!xmllint --format --recover -
" }}}

" Functions {{{

"Change xml namespace prefix function {{{
function! XmlChangeNamespacePrefix(from,to)
  if a:from == "" 
    let from_separator = ""
  else
    let from_separator = ":"
  endif

  if a:to == "" 
    let to_separator = ""
  else
    let to_separator = ":"
  endif

  if a:from == ""
    execute '%s/\v\<(\w+)>' . a:from . from_separator .'/<' . a:to . to_separator .'\1/ge'
    execute '%s/\v\<\/(\w+)>' . a:from . from_separator .'/<\/' . a:to . to_separator .'\1/ge'
    execute '%s/xmlns=/xmlns' . to_separator . a:to . '=/ge'
    execute '%s/type="' . a:from . from_separator . '/type="' . a:to . to_separator . '/ge'
    execute '%s/ref="' . a:from . from_separator . '/ref="' . a:to . to_separator . '/ge'
    execute '%s/base="' . a:from . from_separator . '/base="' . a:to . to_separator . '/ge'
  else
    execute '%s/\v\<(\?)@!' . a:from . from_separator .'/<' . a:to . to_separator .'/ge'
    execute '%s/<\/' . a:from . from_separator .'/<\/' . a:to . to_separator . '/ge'
    execute '%s/xmlns' . from_separator . a:from . '=/xmlns' . to_separator . a:to . '=/ge'
    execute '%s/type="' . a:from . from_separator . '/type="' . a:to . to_separator . '/ge'
    execute '%s/ref="' . a:from . from_separator . '/ref="' . a:to . to_separator . '/ge'
    execute '%s/base="' . a:from . from_separator . '/base="' . a:to . to_separator . '/ge'
  endif
endfunction
" }}}

"Toggle background {{{
function! ToggleBackground()
  if &background == "dark"
    set background=light
  else 
    set background=dark
  endif
endfunction
" }}}

" Search visual selection {{{
function! s:VSetSearch()
  let temp = @s
  norm! gv"sy
  let @/ = '\V' . substitute(escape(@s, '/\'), '\n', '\\n', 'g')
  let @s = temp
endfunction
" }}}

"}}}

