PS1="\u@\h\[\033[01;34m\] \w\[\033[31m\]\n\[\033[0m\]$ "

export EDITOR=vim
#History
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

# Disable flow control(crtl-q ctrl-s)
stty -ixon

#export LC_ALL=sv_SE.UTF-8
#export LANG=sv_SE.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

#To make tmux and vim display colors correctly
export TERM=screen-256color-bce
