PS1="\u@\h\[\033[01;34m\] \w\[\033[31m\]\n\[\033[0m\]$ "

export EDITOR=vim
#History
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

# Disable flow control(crtl-q ctrl-s)
stty -ixon

